#!/usr/bin/env bash

CPU=$(awk -v a="$(awk '/cpu /{print $2+$4,$2+$4+$5}' /proc/stat; sleep 1)" '/cpu /{split(a,b," "); print 100*($2+$4-b[1])/($2+$4+$5-b[2])}'  /proc/stat)

CPU=$(echo $CPU | cut -d '.' -f1)
echo -n "$CPU% $(cat /proc/loadavg | awk '{print $1,$2,$3}') ($(nproc))"
