#!/usr/bin/env bash

PWD=$(pwd)
maxlen=40
leftlen=0
shortened=".."

nPWD=$(pwd)
if [ ${#nPWD} -gt $maxlen ]; then
  offset=$(( ${#nPWD} - $maxlen + $leftlen ))
  nPWD="${nPWD:0:$leftlen}${shortened}${nPWD:$offset:$maxlen}"
else
  nPWD=$(pwd)
fi

echo $nPWD
